### ISSUE TITLE
Consider a prefix

### ISSUE THREAD

**Issue by tylerlittlefield** [VerbalExpressions/RVerbalExpressions#1]
Consider a prefix for auto-populating functions. Something similiar to what tidy packages do. For example, the `str_` prefix from `stringr`. 

Maybe:

1. `rve_` for **R** **V**erbal **E**xpressions?
2. `match_`?
3. `vex_` for **V**erbal **Ex**pression?

https://twitter.com/hadleywickham/status/1101928543485943809
https://twitter.com/danmaclean/status/1101937358289715201

**Comment by b-rodrigues** [comment]
`vex_` sounds like the best option

**Comment by dmi3kno** [comment]
`rx_` or, in the worst case, `vx_`. 
See #5 for details
