### ISSUE TITLE
Add print method for rx_string class

### ISSUE THREAD

**Issue by tylerlittlefield** [VerbalExpressions/RVerbalExpressions#19]
I would like to hide the classes from printing. I'm planning on adding the following to utils.R, [ref](http://adv-r.had.co.nz/S3.html).

```r
print.rx_string <- function(x, ...){
  cat(paste(strwrap(x), collapse = "\n"), "\n", sep = "")
}
```

**Comment by dmi3kno** [comment]
Why would you want to do that? We can decorate the printed `rx` expression, but make it very clear that `rx_digit()` and `\\d` are NOT the same thing

**Comment by tylerlittlefield** [comment]
Ah, so the issue you have is that `cat` removes the additional `\`?

Maybe we do something like:

```r
print.rx_string <- function(x, ...){
  if (is.rx_string(x)) attr(x, "class") <- NULL
  print.default(x, ...)
}

rx_digit()
#> [1] "\\d"

rx_digit() %>% class()
#> [1] "rx_string" "character"
```

This is low hanging fruit, there other things to worry about but I figured this is an easy one. As far as I can tell, the class isn't important to the user so we should hide it.
