### ISSUE TITLE
Rename then

### ISSUE THREAD

**Issue by tylerlittlefield** [VerbalExpressions/RVerbalExpressions#2]
Come up with an alternative name for `then` because the pipe is often interpreted as _then_. Maybe `followed_by` or `exactly`? Or possibly omit entirely.

https://twitter.com/hadleywickham/status/1101928543485943809
https://twitter.com/PStrafo/status/1101929427523461120
https://twitter.com/romain_francois/status/1102204638575636480

**Comment by haozhu233** [comment]
The python implementation of verbal expression uses `find`. Maybe we can align with that?

https://github.com/VerbalExpressions/PythonVerbalExpressions

**Comment by tylerlittlefield** [comment]
Thanks @haozhu233 but [`find()`](https://rverbalexpressions.netlify.com/reference/find.html) actually already exists as an alias to [`then()`](https://rverbalexpressions.netlify.com/reference/then.html). 

`then()` exists purely for semantic reasons when you want something like:

```
library(RVerbalExpressions)

x <- find(value = "abc") %>% 
  anything() %>% 
  then("123")

string <- "abc anything else 123"

grep(x, string, value = TRUE)
#> [1] "abc anything else 123"
```

Instead of `find(value = "abc") %>% anything() %>% find("123")`. At this point, I think I like `exactly()` as a replacement for `then()` the most. This way someone would read it as, find "abc" then anything then exactly "123". I'm also open to just removing `then()` entirely.

**Comment by haozhu233** [comment]
Ah, I see. In this case, I guess either `exactly()` or just removing `then()` works. I personally will allow some variances from verbal languages. ;)

**Comment by tylerlittlefield** [comment]
Done, I've removed `then()` and `any()` in favor of `find()` and `any_of()` per 23b6897. Went ahead and removed `any()` because it collides with `base::any()` and I don't really like the idea of having two functions that do the same thing.
