### ISSUE TITLE
Consider crayon dependency for fancy output

### ISSUE THREAD

**Issue by tylerlittlefield** [VerbalExpressions/RVerbalExpressions#6]
When expressions get large, it might be nice to visualize it in a way that makes it more clear. With `crayon` we could add a function `rx_pretty()` that would adjust the text style, text color, and background color of either the match characters (default) or special characters.

```r
# highlights match or special characters
rx_pretty <- function(.data, txt_style = "bold", txt_col = "black", 
                      bg_col = "white", inverse = FALSE) {
  esc <- c(".", "|", "*", "?", "+", "(", ")", "{", "}", "^", "$", "\\", ":", "=", "[", "]")
  values <- strsplit(.data, "")[[1]]
  
  if(inverse) {
    esc_idx <- which(values %in% esc)
  } else {
    esc_idx <- which(!values %in% esc)
  }
  
  txt <- crayon::make_style(txt_col)
  bg <- crayon::make_style(bg_col, bg = TRUE)
  fancy <- crayon::combine_styles(txt, bg)
  
  cat(replace(values, esc_idx, crayon::style(fancy(values[esc_idx]), as = txt_style)), sep = "")
}

f <- rx() %>% 
  rx_start_of_line() %>% 
  rx_find('http') %>% 
  rx_maybe('s') %>% 
  rx_find('://') %>% 
  rx_maybe('www.') %>% 
  rx_anything_but(' ') %>% 
  rx_end_of_line()
```

Default behavior:

```r
f %>% 
  rx_pretty()
```

<img width="316" alt="Screen Shot 2019-03-08 at 1 30 16 PM" src="https://user-images.githubusercontent.com/35909636/54056924-5a7c8f80-41a6-11e9-8632-7d7d9c7972a8.png">

Inverse behavior:

```r
f %>% 
  rx_pretty(inverse = TRUE)
```

<img width="314" alt="Screen Shot 2019-03-08 at 1 31 27 PM" src="https://user-images.githubusercontent.com/35909636/54056988-8435b680-41a6-11e9-9fc1-4c246c2f420b.png">

Custom behavior:

```r
f %>% 
  rx_pretty(
    txt_style = "italic", 
    txt_col = "white", 
    bg_col = "blue"
    )
```

<img width="315" alt="Screen Shot 2019-03-08 at 1 32 24 PM" src="https://user-images.githubusercontent.com/35909636/54057029-a3ccdf00-41a6-11e9-81b7-3c6d04180b03.png">

**Comment by tylerlittlefield** [comment]
The above `rx_pretty()` (or maybe `rx_highlight()`) would need to be tweaked slightly to highlight situations where special characters should actually be considered matched. In other words, if I want to find __^__, it needs to highlight. Since `sanitize()` adds a backslash to each special character that the user wants to match, we can find those backslash and highlight the character 1 position ahead:

```r
# highlights match or escape characters
rx_pretty <- function(.data, txt_style = "bold", txt_col = "black", 
                      bg_col = "white", inverse = FALSE) {
  esc <- c(".", "|", "*", "?", "+", "(", ")", "{", "}", "^", "$", "\\", ":", "=", "[", "]")
  values <- strsplit(.data, "")[[1]]
  back_slashes <- lapply(strsplit(.data, ''), function(x) which(x == '\\'))
  
  if(inverse) {
    esc_idx <- c(which(values %in% esc), back_slashes[[1]] + 1)
  } else {
    esc_idx <- c(which(!values %in% esc), back_slashes[[1]] + 1)
  }
  
  txt <- crayon::make_style(txt_col)
  bg <- crayon::make_style(bg_col, bg = TRUE)
  fancy <- crayon::combine_styles(txt, bg)
  
  cat(replace(values, esc_idx, crayon::style(fancy(values[esc_idx]), as = txt_style)), sep = "")
}
```

<img width="384" alt="Screen Shot 2019-03-08 at 6 31 04 PM" src="https://user-images.githubusercontent.com/35909636/54065100-64b38380-41d0-11e9-93cb-21472a2705b3.png">

Note how this version correctly highlights the `:` in `://` and `.` in `www.`

**Comment by dmi3kno** [comment]
This might have educational value, but I am not sure it justifies added dependency. The whole point of the package is for user to "not see" the resulting pattern and just pass it to matching function and experience, what Miles McBain calls "[magic moment](https://resources.rstudio.com/rstudio-conf-2019/our-colour-of-magic-the-open-sourcery-of-fantastic-r-packages)".

i am concerned that users will pass "prettied" regex into parsing engine (knowingly or not).

**Comment by tylerlittlefield** [comment]
Agreed, closing.
